name: "Gosec Security Scan"

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - id: checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - name: Run Gosec Security Scanner
      env:
        GOTOOLCHAIN: "go1.24.5"
      uses: securego/gosec@955a68d0d19f4afb7503068f95059f7d0c529017 # v2.22.3
      with:
        args: -exclude G304 ./...
